//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int InvitationNumber { get; set; }
        public string Name { get; set; }
        public System.DateTime DoB { get; set; }
        public string Email { get; set; }
        public bool Verified { get; set; }
        public System.Guid Code { get; set; }
        public string Surname { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> TimeSubmitted { get; set; }
        public Nullable<System.DateTime> TimeVerified { get; set; }
        public Nullable<decimal> TicketCode { get; set; }
    }
}
